language: android
dist: trusty
sudo: false
jdk:
    - oraclejdk8
android:
  components:
    - tools
    - android-28
    - build-tools-28.0.3
    - platform-tools
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
      - "${TRAVIS_BUILD_DIR}/gradle/caches/"
      - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
before_script:
    - bash scripts/prep-key.sh

script:
    - ./gradlew assemblePlayStoreRelease
    - ./gradlew assembleFdroidRelease
    - ./gradlew testPlayStoreReleaseUnitTestCoverage
after_success:
    - bash <(curl -s https://codecov.io/bash)
    - bash scripts/update-apk.sh

branches:
  only:
    - master
    - development
